# Generated by Django 3.1.7 on 2021-04-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTgenerator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='Maths', max_length=30),
        ),
    ]
