# Generated by Django 3.1.7 on 2021-04-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTgenerator', '0002_auto_20210408_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.DateField(auto_now_add=True),
        ),
    ]
